# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yore', models.CharField(max_length=68)),
            ],
        ),
    ]
