# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-08 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dictionary', '0003_word_yore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='yore',
            field=models.ForeignKey(default='anan', on_delete=django.db.models.deletion.CASCADE, to='Dictionary.Yore'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yore',
            name='yore',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
